# coding: utf-8

# flake8: noqa

"""
    Bitflux DownloadStats API

    This is the API for handling stats downloads.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from api_client.api.default_api import DefaultApi

# import ApiClient
from api_client.api_response import ApiResponse
from api_client.api_client import ApiClient
from api_client.configuration import Configuration
from api_client.exceptions import OpenApiException
from api_client.exceptions import ApiTypeError
from api_client.exceptions import ApiValueError
from api_client.exceptions import ApiKeyError
from api_client.exceptions import ApiAttributeError
from api_client.exceptions import ApiException

# import models into sdk package
from api_client.models.download_stats_request import DownloadStatsRequest
from api_client.models.machine_lookup_request import MachineLookupRequest
