# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: downloadstats.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64ownloadstats.proto\x12\rdownloadstats\"\xaa\x01\n\x05Stats\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x04\x12\x10\n\x08unitsize\x18\x03 \x01(\r\x12\x0c\n\x04head\x18\x04 \x01(\r\x12\x0c\n\x04tail\x18\x05 \x01(\r\x12\x0e\n\x06length\x18\x06 \x01(\r\x12*\n\x06system\x18\x07 \x01(\x0b\x32\x1a.downloadstats.SystemStats\x12\x0f\n\x07\x62itflux\x18\x08 \x01(\x0c\"F\n\x0bSystemStats\x12\x11\n\tmem_total\x18\x01 \x01(\x04\x12\x12\n\nswap_total\x18\x02 \x01(\x04\x12\x10\n\x08num_cpus\x18\x03 \x01(\x04\"\x88\x01\n\rMachineLookup\x12\x13\n\x0bmachine_key\x18\x01 \x01(\t\x12\x10\n\x08\x64\x65viceid\x18\x02 \x01(\t\x12\x17\n\x0forganization_id\x18\x03 \x01(\t\x12\x13\n\x0binstance_id\x18\x04 \x01(\t\x12\x12\n\naccount_id\x18\x05 \x01(\t\x12\x0e\n\x06\x61mi_id\x18\x06 \x01(\t\"C\n\x11MachineLookupList\x12.\n\x08machines\x18\x01 \x03(\x0b\x32\x1c.downloadstats.MachineLookupB\rZ\x0b.;generatedb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'downloadstats_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013.;generated'
  _globals['_STATS']._serialized_start=39
  _globals['_STATS']._serialized_end=209
  _globals['_SYSTEMSTATS']._serialized_start=211
  _globals['_SYSTEMSTATS']._serialized_end=281
  _globals['_MACHINELOOKUP']._serialized_start=284
  _globals['_MACHINELOOKUP']._serialized_end=420
  _globals['_MACHINELOOKUPLIST']._serialized_start=422
  _globals['_MACHINELOOKUPLIST']._serialized_end=489
# @@protoc_insertion_point(module_scope)
