# coding: utf-8

# flake8: noqa
"""
    Bitflux DownloadStats API

    This is the API for handling stats downloads.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from api_client.models.download_stats_request import DownloadStatsRequest
from api_client.models.machine_lookup_request import MachineLookupRequest
